# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0018_auto_20180905_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info',
            name='callnumber',
            field=models.IntegerField(),
        ),
    ]
